### ISSUE TITLE
Please provide public URL to which we can connect

### ISSUE THREAD

**Issue by pjbins** [VesseliQ/VesseliQ#1]
VesselIQ now has 3 domains: .info .online and .nl
We want to show landing page stating our mission + coming soon.
Also this landing page should show our logo.

**Comment by jrversteegh** [comment]
The [README](https://github.com/VesseliQ/VesseliQ/blob/main/README.md) is supposed to serve as a [Profile page](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/managing-your-profile-readme). However, I don't see this working at the moment. Maybe it doesn't work for organizations, maybe you'd have to have a paid organizations account first. Not sure.

For the moment, I think it's easiest to link to the following ip address: 5.79.75.233. I will setup a basic site there for the time being. We can later switch to google cloud or aws or something.

**Comment by jrversteegh** [comment]
Looking a little further, there also appear to be [github pages](https://pages.github.com), which I've setup an can be viewed [here](https://vesseliq.github.io). This is being served from [this repo](https://github.com/VesseliQ/vesseliq.github.io). This provides a little less freedom but may be simpler for the moment.

**Comment by pjbins** [comment]
Fine for now. Please advise the public URL that we can forward our announcement as well as our own Vesselperformancecentre.com references to.

**Comment by jrversteegh** [comment]
[https://vesseliq.github.io](https://vesseliq.github.io)

**Comment by jrversteegh** [comment]
The alternative is [https://vesseliq.orca-st.com](https://vesseliq.orca-st.com), which is where I'll deploy the software for the time being.
